[project]
name = "livellm_proxy"
version = "0.1.0"
description = "client for the livellm proxy client with prod features"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.27.0",
    "pydantic>=2.0.0",
]
